pointcloud_to_laserscan:
  ros__parameters:
    target_frame: "camera_link"            # Frame ID of the RealSense camera
    input_cloud_topic: "/camera/camera/depth/color/points"  # Replace with your actual PointCloud2 topic
    output_scan_topic: "/scan"             # Topic where LaserScan messages will be published
    # min_height: 0.0                        # Minimum height to filter points
    # max_height: 1.0                        # Maximum height to filter points
    # angle_min: -1.5708                     # -90 degrees in radians
    # angle_max: 1.5708                      # 90 degrees in radians
    # angle_increment: 0.0174533            # 1 degree in radians
    # scan_time: 0.0                         # Use default
    # range_min: 0.2                         # Minimum range in meters
    # range_max: 10.0                        # Maximum range in meters
    # use_inf: false                         # Whether to include infinite ranges
    # bridge_options: "compressedDepth"      # Use appropriate bridge options

