rtabmap:
  
  # RVIZ
  # rtabmapviz: true # MAKE SURE TO COMMENT THIS OUT DURING COMPETITION TO REDUCE BANDWIDTH

  # Topic names
  # depth_topic: /camera/camera/depth/image_rect_raw
  # rgb_topic: /camera/camera/color/image_raw
  # camera_info_topic: /camera/camera/color/camera_info
  # depth_topic': '/camera/camera_1/aligned_depth_to_color/image_raw'
  # rgb_topic': '/camera/camera_1/color/image_raw'
  # camera_info_topic: '/camera/camera_1/color/camera_info'
  # scan_topic: /scan
  # imu_topic: /imu/data
  
  # RTAB Map Functionality
  # localization: true
  # approx_sync: true
  # visual_odometry: true

  # RTAB Map Frames and TFs
  # publish_tf: true
  # map_frame_id: map
  # odom_frame_id: odom
  # frame_id: base_link

  # Occupancy Grid
  Grid/FromDepth: true
  Grid/3D: false
  Grid/CellSize: 0.05
  # Grid/DepthDecimation: 5 # Change as needed
  Grid/RangeMin: 0.3
  Grid/RangeMax: 5.0
  grid_map_publisher_rate: 1.0
  # grid_frame_id: map

  # Publishing/Subscribing
  # queue_size: 10
  # wait_imu_to_init': true'
  # subscribe_depth: true
  # subscribe_rgb: true
  # subscribe_stereo: false
  # subscribe_scan: true
  'Mem/IncrementalMemory': 'true'