slam_toolbox:
  ros__parameters:
    use_sim_time: false
    slam_mode: "mapping"  # Options: "mapping", "localization"
    map_frame: "map"
    tracking_frame: "laser"
    published_frame: "odom"
    odom_frame: "odom"
    provide_odom_frame: true
    use_pose_extrapolator: true
    resolution: 0.05
    publish_period_sec: 0.5
    # Add other parameters as needed

