serial_description:
  motors:
    type: write
    topic: 
    m1:
      speed: 0
      direction: 0
    m2:
      speed: 0
      direction: 0
  actuator_target:
    type: write
    a1: 0
    a2: 0
    a3: 0
  actuator_position:
    type: read
    a1: 0
    a2: 0
    a3: 0
  status_leds:
    type: write
    red: false    # Status of red LED (boolean)
    yellow: false # Status of yellow LED (boolean)
    green: false  # Status of green LED (boolean)
    blue: false   # Status of blue LED (boolean)
  lcd_display:
    type: write
    line_1: ""  # Text for the first line of the 2x16 LCD display (string)
    line_2: ""  # Text for the second line of the 2x16 LCD display (string)