serial_node:
  ros__parameters:
    subscribe:
      motor_topic: "/motors"
      actuator_target_topic: "/actuators"
      status_led_topic: "/status_leds"
      lcd_input_topic: "/lcd_input"
    publish:
      actuator_feedback_topic: "/actuator_feedback"