serial_node:
  ros__parameters:
    serial_device: "/dev/ttyUSB0"
    baud_rate: 115200

convert_serial_node:
  ros__parameters:
    motor_ctrl_topic: "/motor_control"
    actuator_ctrl_topic: "/actuator_control"
    actuator_feedback_topic: "/actuator_feedback"