lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true
    lifecycle_nodes:
      # - map_server
      - amcl
      - planner_server
      - controller_server
      - bt_navigator
      - recovery_server

# map_server:
#   ros__parameters:
#     use_sim_time: false
#     yaml_filename: "/home/user/ros2_ws/src/navigation/maps/map.yaml"
#     frame_id: "map"
#     publish_frequency: 1.0
#     subscribe_to_updates: true
#     use_compressed_map: false

amcl:
  ros__parameters:
    use_sim_time: false
    map_topic: /rtabmap/map
    scan_topic: /scan
    odom_topic: /rtabmap/odom
    transform_tolerance: 1.0
    min_particles: 500
    max_particles: 2000

planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    use_sim_time: true
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: true
      allow_unknown: true

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    costmap_update_timeout: 0.3
    min_x_velocity_threshold: 0.01
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.01
    failure_tolerance: 0.3
    odom_topic: "/rtabmap/odom"
    progress_checker_plugin: ["progress_checker"]
    goal_checker_plugin: ["goal_checker"]
    controller_plugins: ["DWBLocalPlanner"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: True
    DWBLocalPlanner:
      plugin: "dwb_core::DWBLocalPlanner"
      critics: ["RotateToGoal", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]


# costmap_common:
#   ros__parameters:
#     footprint: "[[0.15, 0.15], [-0.15, 0.15], [-0.15, -0.15], [0.15, -0.15]]"
#     inflation_radius: 0.2
#     resolution: 0.05
#     robot_radius: 0.15
#     obstacle_layer:
#       enabled: true
#       max_obstacle_height: 2.0
#       min_obstacle_height: 0.0
#       obstacle_range: 2.5
#       raytrace_range: 3.0
#     cost_scaling_factor: 10.0
#     inflation_layer:
#       enabled: true

global_costmap:
  global_costmap:
    ros__parameters:
      footprint: "[[0.15, 0.15], [-0.15, 0.15], [-0.15, -0.15], [0.15, -0.15]]"
      resolution: 0.05
      footprint_padding: 0.03
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: false
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        footprint_clearing_enabled: true
        max_obstacle_height: 2.0
        combination_method: 1
        scan:
          topic: /scan
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          inf_is_valid: false
        static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: true
        subscribe_to_updates: true
        transform_tolerance: 0.1
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.55
        cost_scaling_factor: 1.0
        inflate_unknown: false
        inflate_around_unknown: true
      always_send_full_costmap: True
      service_introspection_mode: "disabled"


local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: "/rtabmap/odom"
      robot_base_frame: base_link
      use_sim_time: false
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      service_introspection_mode: "disabled"

bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.1
    filter_duration: 0.3
    service_intropection_mode: "disabled"
    # default_nav_to_pose_bt_xml: replace/with/path/to/bt.xml # or $(find-pkg-share my_package)/behavior_tree/my_nav_to_pose_bt.xml
    # default_nav_through_poses_bt_xml: replace/with/path/to/bt.xml # or $(find-pkg-share my_package)/behavior_tree/my_nav_through_poses_bt.xml
    # always_reload_bt_xml: false
    # goal_blackboard_id: goal
    # goals_blackboard_id: goals
    # path_blackboard_id: path
    waypoint_statuses_blackboard_id: waypoint_statuses
    navigators: ['navigate_to_pose', 'navigate_through_poses']
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator" # In Iron and older versions, "/" was used instead of "::"
      enable_groot_monitoring: false
      # groot_server_port: 1667
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator" # In Iron and older versions, "/" was used instead of "::"
      enable_groot_monitoring: false
      # groot_server_port: 1669
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_is_stopped_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
    error_code_name_prefixes:
      - assisted_teleop
      - backup
      - compute_path
      - dock_robot
      - drive_on_heading
      - follow_path
      - nav_thru_poses
      - nav_to_pose
      - spin
      - route
      - undock_robot
      - wait

recovery_server:
  ros__parameters:
    use_sim_time: false
