amcl:
  ros__parameters:
    use_map_topic: true
    scan_topic: scan
    base_frame_id: base_link
    odom_frame_id: odom
    global_frame_id: map
    transform_tolerance: 0.2
    set_initial_pose: true

bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    odom_topic: odom
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

controller_server:
  ros__parameters:
    use_sim_time: false
    odom_topic: odom
    base_frame_id: base_link
    robot_radius: 0.25
    min_vel_x: 0.0
    max_vel_x: 0.5
    min_vel_y: 0.0
    max_vel_y: 0.0
    min_speed_xy: 0.0
    max_speed_xy: 0.5
    max_speed_theta: 1.0
    min_speed_theta: 0.0

local_costmap:
  ros__parameters:
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.0
    resolution: 0.05
    footprint: "[[-0.3, -0.3], [-0.3, 0.3], [0.3, 0.3], [0.3, -0.3]]"
    global_frame: odom
    robot_radius: 0.25
    plugins: ["obstacle_layer", "inflation_layer"]

global_costmap:
  ros__parameters:
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.0
    resolution: 0.05
    footprint: "[[-0.3, -0.3], [-0.3, 0.3], [0.3, 0.3], [0.3, -0.3]]"
    global_frame: map
    robot_radius: 0.25
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
